services:
  backend:
    build: ./backend
    ports:
      - "5050:5050" 
    networks:
      - shop_network
    environment:
      - DB_HOST=mysql_db
      - DB_USER=root 
      - DB_PASSWORD=rootpassword 
      - DB_NAME=shopping_db 
    depends_on:
      - mysql_db

  frontend:
    build: ./frontend
    ports:
      - "80:80"  
    networks:
      - shop_network
    depends_on:
      - backend
      
  mysql_db:
    image: ./database 
    ports:
      - "3306:3306"  
    networks:
      - shop_network
    environment:
      - MYSQL_DATABASE=shopping_db
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - mysql-data:/data/db
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  shop_network:
  
volumes:
  mysql-data:
